name: vr_player
description: The `VrPlayer` plugin allows for the seamless playback of 360° and VR videos on both Android and iOS platforms.
version: 0.1.2
homepage: "https://github.com/flutterwtf/VR-Player"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: wtf.flutter.vr_player
        pluginClass: VrPlayer
      ios:
        pluginClass: VrPlayer
